[pytest]
# Needed for DNS async tests ---
asyncio_mode = auto

# Custom markers
markers =
    e2e: marks tests as end-to-end
    slow: marks slow tests

# Output and discovery settings
addopts = -q

# Where pytest should look for tests
testpaths = 
    e2e_tests
    src/scrub/tests

# Ensures imports like 'from main import app' work correctly
pythonpath = src
