[pytest]
# Custom markers
markers =
    e2e: marks tests as end-to-end
    slow: marks slow tests

addopts = -q

# Where pytest should look for tests
testpaths = 
    e2e_tests
    src/mail-validation/tests
