// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/lists": {
    params: {};
  };
  "/integrations": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/api": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/settings/general": {
    params: {};
  };
  "/settings/account": {
    params: {};
  };
  "/settings/analytics": {
    params: {};
  };
  "/settings/history": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/lists" | "/integrations" | "/docs" | "/api" | "/auth/callback" | "/settings" | "/settings/general" | "/settings/account" | "/settings/analytics" | "/settings/history";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/lists.tsx": {
    id: "routes/lists";
    page: "/lists";
  };
  "routes/integrations.tsx": {
    id: "routes/integrations";
    page: "/integrations";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
  "routes/api.tsx": {
    id: "routes/api";
    page: "/api";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings" | "/settings/general" | "/settings/account" | "/settings/analytics" | "/settings/history";
  };
  "routes/settings.index.tsx": {
    id: "routes/settings.index";
    page: "/settings";
  };
  "routes/settings.general.tsx": {
    id: "routes/settings.general";
    page: "/settings/general";
  };
  "routes/settings.account.tsx": {
    id: "routes/settings.account";
    page: "/settings/account";
  };
  "routes/settings.analytics.tsx": {
    id: "routes/settings.analytics";
    page: "/settings/analytics";
  };
  "routes/settings.history.tsx": {
    id: "routes/settings.history";
    page: "/settings/history";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/lists": typeof import("./app/routes/lists.tsx");
  "routes/integrations": typeof import("./app/routes/integrations.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/api": typeof import("./app/routes/api.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/settings.index": typeof import("./app/routes/settings.index.tsx");
  "routes/settings.general": typeof import("./app/routes/settings.general.tsx");
  "routes/settings.account": typeof import("./app/routes/settings.account.tsx");
  "routes/settings.analytics": typeof import("./app/routes/settings.analytics.tsx");
  "routes/settings.history": typeof import("./app/routes/settings.history.tsx");
};