import asyncio
import math

import sentry_sdk
from redis import Redis
from rq import Queue
from sqlalchemy.pool import NullPool

from scrub.models.history_store import HistoryStore
from scrub.models.integration_store import IntegrationStore
from scrub.models.validation_job_store import ValidationJobStore
from scrub.repositories.user_repository import UserRepository
from scrub.services.listmonk import ListmonkClient
from scrub.services.validation_service import validate_email_internal
from scrub.settings import Settings

settings = Settings()

if settings.sentry_dsn:
    sentry_sdk.init(
        dsn=settings.sentry_dsn,
        environment=settings.sentry_environment,
        traces_sample_rate=0.05,
        send_default_pii=False,
    )


def get_queue() -> Queue:
    return Queue(connection=Redis.from_url(settings.redis_url))


def _get_listmonk_client(integration_id: int) -> ListmonkClient | None:
    """Look up the integration by id and return a client, or None."""
    store = IntegrationStore(settings.scrub_db_url, poolclass=NullPool)
    integration = store.get_by_id(integration_id)
    if not integration:
        return None
    cfg = integration.config
    return ListmonkClient(cfg["url"], cfg["username"], cfg["api_token"])


def start_list_validation(
    integration_id: int, list_id: int, user_id: str, request_id: str
) -> None:
    """
    Kick off paged validation for a Listmonk list.
    Fetches total subscriber count then enqueues one validate_list_page job per page.
    request_id is generated by the caller (router) so the frontend can track progress.
    """
    client = _get_listmonk_client(integration_id)
    if not client:
        return

    total = client.subscribers_total(list_id)
    pages = math.ceil(total / 100) or 1

    # get_lists() returns MailingList pydantic objects — use attribute access
    lists_info = client.get_lists()
    list_name = None
    for lst in lists_info:
        if lst.id == list_id:
            list_name = lst.name
            break

    # Update the job record created by the router with real totals/name, then mark running.
    # (Router creates a pending record immediately so the frontend can poll right away.)
    job_store = ValidationJobStore(settings.scrub_db_url, poolclass=NullPool)
    job_store.set_start_info(request_id, total_items=total, list_name=list_name)
    job_store.start_job(request_id)

    q = get_queue()
    for page in range(1, pages + 1):
        q.enqueue(
            validate_list_page,
            integration_id,
            list_id,
            page,
            100,
            user_id,
            request_id,
            job_timeout=600,  # 10 min — 100 DNS lookups at 2s each + overhead
        )


def validate_list_page(
    integration_id: int,
    list_id: int,
    page: int,
    page_size: int,
    user_id: str,
    request_id: str,
) -> None:
    """
    Validate one page of subscribers for a Listmonk list.
    Runs all emails in the batch concurrently on a single event loop,
    persists results to history, and blocks invalid subscribers.
    """
    client = _get_listmonk_client(integration_id)
    if not client:
        return

    subscribers = client.subscribers_page(list_id, page, page_size)
    if not subscribers:
        return

    emails = [sub.get("email", "") for sub in subscribers]

    async def _run_batch():
        sem = asyncio.Semaphore(
            20
        )  # cap concurrent DNS lookups to prevent event loop stalls

        async def bounded_validate(email: str):
            async with sem:
                return await validate_email_internal(email)

        return await asyncio.wait_for(
            asyncio.gather(
                *[bounded_validate(email) for email in emails],
                return_exceptions=True,
            ),
            timeout=120,  # hard backstop: 20 concurrent × ~3s per lookup × 2 rounds + overhead
        )

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        raw_results = loop.run_until_complete(_run_batch())
    except asyncio.TimeoutError:
        # Entire batch exceeded the 120s backstop — treat all emails as errored
        # and mark the job failed so it doesn't stay stuck in "running" forever.
        job_store = ValidationJobStore(settings.scrub_db_url, poolclass=NullPool)
        job_store.fail_job(request_id, f"Page {page} validation timed out after 120s")
        return
    finally:
        loop.close()

    history_entries: list[dict] = []
    to_block_ids: list[int] = []

    for sub, result in zip(subscribers, raw_results):
        email = sub.get("email", "")
        if isinstance(result, Exception):
            history_entries.append(
                {
                    "email": email,
                    "is_valid": False,
                    "request_id": request_id,
                    "user_id": user_id,
                }
            )
            continue
        history_entries.append(
            {
                "email": email,
                "is_valid": result["ok"],
                "quality_score": result.get("quality_score"),
                "checks": result.get("checks"),
                "attributes": result.get("attributes"),
                "request_id": request_id,
                "user_id": user_id,
            }
        )
        if not result["ok"]:
            to_block_ids.append(sub["id"])

    HistoryStore(settings.scrub_db_url, poolclass=NullPool).save_many(history_entries)

    if history_entries:
        UserRepository(settings.scrub_db_url, poolclass=NullPool).record_usage(
            {"sub": user_id}, count=len(history_entries)
        )

    # Update job progress
    valid_count = sum(1 for e in history_entries if e.get("is_valid"))
    invalid_count = len(history_entries) - valid_count
    job_store = ValidationJobStore(settings.scrub_db_url, poolclass=NullPool)
    current_job = job_store.get_by_request_id(request_id, user_id)
    if current_job:
        new_processed = current_job.processed_items + len(history_entries)
        new_valid = current_job.valid_count + valid_count
        new_invalid = current_job.invalid_count + invalid_count
        # Check if this was the last page
        if new_processed >= current_job.total_items:
            job_store.complete_job(
                request_id=request_id,
                processed_items=new_processed,
                valid_count=new_valid,
                invalid_count=new_invalid,
            )
        else:
            job_store.update_progress(
                request_id=request_id,
                processed_items=new_processed,
                valid_count=new_valid,
                invalid_count=new_invalid,
            )

    if to_block_ids:
        client.block_subscribers_by_ids(to_block_ids)
